import type { Applicant, Property } from "./types";

type SeedApplicant = Omit<Applicant, "status">;

export const mockProperties: Property[] = [
  {
    id: "p1",
    address: "12/48 Bondi Road",
    suburb: "Bondi",
    city: "Sydney NSW 2026",
    weeklyRent: 850,
    bedrooms: 2,
    bathrooms: 1,
    parking: 1,
    status: "active",
    imageUrl:
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1200&q=80",
    requiredDocuments: ["id", "proof_of_income", "bank_statements", "rental_history", "references"],
    createdAt: "2025-03-12",
  },
  {
    id: "p2",
    address: "7 Acland Street",
    suburb: "St Kilda",
    city: "Melbourne VIC 3182",
    weeklyRent: 620,
    bedrooms: 1,
    bathrooms: 1,
    parking: 0,
    status: "active",
    imageUrl:
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
    requiredDocuments: ["id", "proof_of_income", "rental_history", "references"],
    createdAt: "2025-03-28",
  },
  {
    id: "p3",
    address: "204/91 Macquarie Street",
    suburb: "Sydney CBD",
    city: "Sydney NSW 2000",
    weeklyRent: 1200,
    bedrooms: 3,
    bathrooms: 2,
    parking: 2,
    status: "active",
    imageUrl:
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    requiredDocuments: [
      "id",
      "passport",
      "proof_of_income",
      "bank_statements",
      "employment_letter",
      "rental_history",
      "references",
    ],
    createdAt: "2025-04-02",
  },
  {
    id: "p4",
    address: "33 Petrie Terrace",
    suburb: "Paddington",
    city: "Brisbane QLD 4064",
    weeklyRent: 540,
    bedrooms: 2,
    bathrooms: 1,
    parking: 1,
    status: "leased",
    imageUrl:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    requiredDocuments: ["id", "proof_of_income", "rental_history"],
    createdAt: "2025-02-18",
  },
];

export const mockApplicants: SeedApplicant[] = [
  // Bondi
  {
    id: "a1",
    propertyId: "p1",
    name: "Olivia Bennett",
    email: "olivia.bennett@example.com",
    phone: "+61 412 555 098",
    occupation: "Senior UX Designer",
    weeklyIncome: 2700,
    submittedDocuments: ["id", "proof_of_income", "bank_statements", "rental_history", "references"],
    rentalHistory: {
      yearsRenting: 6,
      onTimePaymentsPct: 100,
      referenceQuality: "strong",
      notes: "Glowing reference from previous agent. Renewed lease twice.",
    },
    appliedAt: "2025-04-14",
    notes: "Open to a 12-month lease, can move in immediately.",
  },
  {
    id: "a2",
    propertyId: "p1",
    name: "Marcus Chen",
    email: "m.chen@example.com",
    phone: "+61 423 117 882",
    occupation: "Software Engineer",
    weeklyIncome: 2200,
    submittedDocuments: ["id", "proof_of_income", "bank_statements", "references"],
    rentalHistory: {
      yearsRenting: 3,
      onTimePaymentsPct: 96,
      referenceQuality: "ok",
    },
    appliedAt: "2025-04-15",
  },
  {
    id: "a3",
    propertyId: "p1",
    name: "Priya Shah",
    email: "priya.shah@example.com",
    phone: "+61 401 998 220",
    occupation: "Marketing Lead",
    weeklyIncome: 1700,
    submittedDocuments: ["id", "proof_of_income"],
    rentalHistory: {
      yearsRenting: 2,
      onTimePaymentsPct: 88,
      referenceQuality: "ok",
    },
    appliedAt: "2025-04-16",
  },
  {
    id: "a4",
    propertyId: "p1",
    name: "Jake Robertson",
    email: "jake.r@example.com",
    phone: "+61 433 552 901",
    occupation: "Hospitality",
    weeklyIncome: 1100,
    submittedDocuments: ["id"],
    rentalHistory: {
      yearsRenting: 1,
      onTimePaymentsPct: 70,
      referenceQuality: "weak",
    },
    appliedAt: "2025-04-13",
  },
  // St Kilda
  {
    id: "a5",
    propertyId: "p2",
    name: "Hannah Williams",
    email: "hannah.w@example.com",
    phone: "+61 422 010 553",
    occupation: "Nurse",
    weeklyIncome: 1900,
    submittedDocuments: ["id", "proof_of_income", "rental_history", "references"],
    rentalHistory: { yearsRenting: 5, onTimePaymentsPct: 99, referenceQuality: "strong" },
    appliedAt: "2025-04-10",
  },
  {
    id: "a6",
    propertyId: "p2",
    name: "Tom Becker",
    email: "tom.b@example.com",
    phone: "+61 410 887 233",
    occupation: "Teacher",
    weeklyIncome: 1500,
    submittedDocuments: ["id", "proof_of_income", "references"],
    rentalHistory: { yearsRenting: 4, onTimePaymentsPct: 92, referenceQuality: "ok" },
    appliedAt: "2025-04-12",
  },
  // Macquarie
  {
    id: "a7",
    propertyId: "p3",
    name: "Sophie Laurent",
    email: "sophie.l@example.com",
    phone: "+61 414 220 998",
    occupation: "Investment Banker",
    weeklyIncome: 4200,
    submittedDocuments: [
      "id",
      "passport",
      "proof_of_income",
      "bank_statements",
      "employment_letter",
      "rental_history",
      "references",
    ],
    rentalHistory: { yearsRenting: 8, onTimePaymentsPct: 100, referenceQuality: "strong" },
    appliedAt: "2025-04-15",
  },
  {
    id: "a8",
    propertyId: "p3",
    name: "Daniel Park",
    email: "d.park@example.com",
    phone: "+61 412 002 884",
    occupation: "Consultant",
    weeklyIncome: 3100,
    submittedDocuments: ["id", "proof_of_income", "bank_statements", "employment_letter"],
    rentalHistory: { yearsRenting: 4, onTimePaymentsPct: 94, referenceQuality: "ok" },
    appliedAt: "2025-04-16",
  },
];
